version: "3.9"
services:
  api:
    build:
      context: api
      dockerfile: Dockerfile
    volumes:
      - ./api:/home/api
    ports:
      - 2000:2000
  web:
    build:
      context: web
      dockerfile: Dockerfile
    volumes:
      - ./web:/home/web
    ports:
      - 3000:3000
  db:
    image: postgres:14.3-alpine3.15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=scoreboard
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data/

volumes:
  db: